### ISSUE TITLE
Occasional keyerror during dm deletion

### ISSUE THREAD

**Issue by lijok** [lijok/discord_nuke#2]
Traceback (most recent call last):
  File "main.py", line 362, in <module>
    delete_all(discord, channel_id, scope=scope)
  File "main.py", line 298, in delete_all
    messages = (discord.get_own_dm_messages(id) if scope == 'DM'
  File "main.py", line 229, in get_own_dm_messages
    if messages['total_results'] == 0:
KeyError: 'total_results'

**Comment by lijok** [comment]
Occurs when you delete one dm then select to delete another
